### ISSUE TITLE
Teams and Collaborators don't seem to work

### ISSUE THREAD

**Issue by nikolay** [probot/configurer#28]
I keep making changes and push, but nothing changes.

**Comment by bkeepers** [comment]
Yeah, unfortunately GitHub Apps don't support the API endpoints for this feature yet. I updated the docs in 3ae86b615010ba0585714a8aa10211071b9c08f7. It should just start working once those APIs are implemented.

**Comment by simonvanderveldt** [comment]
@bkeepers Is there a place where one can check which API endpoints are supported by GitHub Apps? Was wondering if it should/would work now, but am unable to find a definitive answer.
