### ISSUE TITLE
Read configuration file from some remote URL

### ISSUE THREAD

**Issue by danielbachhuber** [probot/configurer#35]
It would be neat if my `.github/config` file could inherit from a remote URL, such that I could have some centralized config shared amongst repos, with some local overrides.

**Comment by bkeepers** [comment]
This is what I had in mind for https://github.com/probot/configurer/issues/29. Let me know if that doesn't cover it.

**Comment by danielbachhuber** [comment]
Lol. Who's that @danielbachhuber guy that already commented.
